(function (HSParameterType) {
    HSParameterType[HSParameterType["Default"] = 42] = "Default";
    HSParameterType[HSParameterType["LineWidth"] = 43] = "LineWidth";
    HSParameterType[HSParameterType["LineColor"] = 44] = "LineColor";
    HSParameterType[HSParameterType["RandomLow"] = 45] = "RandomLow";
    HSParameterType[HSParameterType["RandomHigh"] = 46] = "RandomHigh";
    HSParameterType[HSParameterType["Variable"] = 47] = "Variable";
    HSParameterType[HSParameterType["VariableValue"] = 48] = "VariableValue";
    HSParameterType[HSParameterType["Conditional"] = 49] = "Conditional";
    HSParameterType[HSParameterType["HSObject"] = 50] = "HSObject";
    HSParameterType[HSParameterType["Sound"] = 51] = "Sound";
    HSParameterType[HSParameterType["Event"] = 52] = "Event";
    HSParameterType[HSParameterType["SetText"] = 53] = "SetText";
    HSParameterType[HSParameterType["Object"] = 54] = "Object";
    HSParameterType[HSParameterType["TextOnly"] = 55] = "TextOnly";
    HSParameterType[HSParameterType["Scene"] = 56] = "Scene";
    HSParameterType[HSParameterType["MultiPurposeNumberDefault"] = 57] = "MultiPurposeNumberDefault";
    HSParameterType[HSParameterType["Product"] = 58] = "Product";
    HSParameterType[HSParameterType["Rhythm"] = 59] = "Rhythm";
    HSParameterType[HSParameterType["MusicNote"] = 60] = "MusicNote";
    HSParameterType[HSParameterType["Instrument"] = 61] = "Instrument";
})(module.exports.HSParameterType = {});